[package]
name = "gaming-mouse-control-center"
version = "0.1.1"
description = "8K Gaming Mouse Control Center"
authors = ["Hua Xuan Design"]
edition = "2021"

[lib]
name = "gaming_mouse_control_center_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
hidapi = "2"
